### ISSUE TITLE
Development Roadmap

### ISSUE THREAD

**Issue by jensen-yan** [OpenXiangShan/GEM5#181]
Here is the development roadmap. Contributions and feedback are welcome.
# Project Roadmap

## 1. Dynamic Vector Length Support

- [ ] Implement variable vector length (not fixed at 128).

## 2. Value Prediction

- [ ] Loop iterators(#188 ). 
- [ ] vl prediction. 
- [ ] Generic value prediction(#188 ).

## 3. Speculative Memory Bypassing

- [ ] Table-less implementation.
- [ ] Dynamic bypassing.

## 4. Top-down Analysis Framework

- [ ] Further breakdown of details in top-down approach.
- [ ] Detailed documentation for top-down methodology.
- [ ] TIP/TEA integration.

## 5. Front-End Optimizations

- [ ] 8-wide instruction issue
- [ ] Two-taken branch predictor
- [ ] uBTB: Expand for improved timing guarantees.
- [ ] TAGE:
  - [ ] Increase from 5-table to 10-table cascaded comparison for better timing and reduced MPKI.
  - [ ] Compare increasing the number of levels versus increasing the number of entries.
- [ ] Fetch Pipeline:
  - [ ] Refactor for two-taken + two-fetch mechanism.
  - [ ] Enable single-cycle access to multiple cache lines.
  - [ ] Clean up fetch and cache pipeline code.

## 6. Calibration

- [x] Detailed load/store pipeline: challenging, important, but not urgent. (#186 )
- [x] Calibrate functional unit (FU). (#185 )
- [x] Calibrate scheduler. (#185 )
- [ ] Calibrate Memory speculation. (Developing)
- [ ] Calibrate Prefetchers. (Developing)

## 7.Hypervisor (H) Extension Improvements

- [ ] OpenSBI + kernel support.
- [ ] MMU & prefetch optimizations

## 8.Cliff - Microbenchmark for Calibration

- [ ] Cliff for frontend testing.
- [ ] Cliff for prefetcher evaluation.

## How to Contribute to This Roadmap

1. To add a new task, use the following format:
   ```
   - [ ] Task description
   ```

2. To mark a task as completed, change `[ ]` to `[x]`:
   ```
   - [x] Completed task
   ```

3. To link to an issue or pull request, use the `#` symbol followed by the issue/PR number:
   ```
   - [ ] Implement feature X (#123)
   ```
- [ ] Implement feature X (#123)
4. Feel free to add comments or additional information using HTML comment syntax:
   ```
   <!-- This is a comment that won't be visible in the rendered markdown -->
   ```

**Comment by zybzzz** [comment]
I am excited to see the RoadMap, and the toolchain provided by Xiangshan has significantly improved the execution speed of gem5 and shortened the debugging time.

I'm a current master's student in computer architecture, and my current work is focused on **value prediction**, but I'm also interested in top-down analysis methods. I'd be happy to contribute to xs-gem5, but considering that xs-gem5 is in the internal development phase, I am unsure whether it is open to contributions from ordinary developers in the open-source community.

If so, could I send an email to the appropriate people? I'll describe my background, what I can do, and what I'd like to do in the email.

@jensen-yan

**Comment by shinezyy** [comment]
> I am excited to see the RoadMap, and the toolchain provided by Xiangshan has significantly improved the execution speed of gem5 and shortened the debugging time.
> 
> I'm a current master's student in computer architecture, and my current work is focused on **value prediction**, but I'm also interested in top-down analysis methods. I'd be happy to contribute to xs-gem5, but considering that xs-gem5 is in the internal development phase, I am unsure whether it is open to contributions from ordinary developers in the open-source community.
> 
> If so, could I send an email to the appropriate people? I'll describe my background, what I can do, and what I'd like to do in the email.
> 
> @jensen-yan


xs-gem5 has ended internal development phase, and is now open to contributions!

On contributing to topdown/value prediction, we can open another issue to discuss. And you can also e-mail me (zhouyaoyang@bosc.ac.cn or archshinez@outlook.com) and @jensen-yan

**Comment by muke101** [comment]
Hi, this is really cool and I hope a lot of progress can be made in implementing these more advanced techniques.

I've Implemented a newer MDP algorithm called PHAST (https://webs.um.es/aros/papers/pdfs/sskim-hpca24.pdf) based on another Gem5 fork. It achieves much higher accuracy than Store Sets (the open source version at least. I see this repo implements a better version that I'm keen to evaluate PHAST against too). It feels it'd be appropriate to aim to include the algorithm in this fork too. The repo is here: https://gitlab.com/muke101/gem5-phast

I wouldn't have time to integrate it to this repo myself, but I'd be happy to offer help to anyone who might want to take it on.

**Comment by happy-lx** [comment]
> Hi, this is really cool and I hope a lot of progress can be made in implementing these more advanced techniques.
> 
> I've Implemented a newer MDP algorithm called PHAST (https://webs.um.es/aros/papers/pdfs/sskim-hpca24.pdf) based on another Gem5 fork. It achieves much higher accuracy than Store Sets (the open source version at least. I see this repo implements a better version that I'm keen to evaluate PHAST against too). It feels it'd be appropriate to aim to include the algorithm in this fork too. The repo is here: https://gitlab.com/muke101/gem5-phast
> 
> I wouldn't have time to integrate it to this repo myself, but I'd be happy to offer help to anyone who might want to take it on.


@muke101 Thank you very much for providing the PHAST implementation! 

It does indeed have the potential to offer greater performance gains than the current StoreSet algorithm in XS-GEM5. 

We will take a look at your implementation and try it out soon. Thank you.
